router/urls.py
from __future__ import unicode_literals

from django.urls import path
from django.conf.urls import url, include
from rest_framework import routers

from bible import views as bibleviews
from commentary import views as commentaryviews

router = routers.DefaultRouter()
router.register('versions', bibleviews.VersionViewSet)
router.register('books', bibleviews.BooksViewSet)
router.register('chapters', bibleviews.ChaptersViewSet)
router.register('verses', bibleviews.VersesViewSet)
router.register('commentary', commentaryviews.CommentaryTextViewSet)

urlpatterns = router.urls

bible/models.py
"""models"""

from django.db import models
from django.shortcuts import reverse

from helpers.models import TimeStampedModel
from helpers.fields import AutoSlugField, AutoMultipleSlugField

class Version(TimeStampedModel):
    name = models.CharField(max_length=100, unique=True)
    slug = AutoSlugField(set_using='name')

    class Meta:
        ordering = ('name', )

    def __str__(self):
        return self.name

class Book(TimeStampedModel):
    version = models.ForeignKey(Version, on_delete=models.CASCADE)
    name = models.CharField(max_length=50, unique=True)
    alt_name = models.CharField(max_length=100, blank=True)
    position = models.IntegerField()
    testament = models.CharField(max_length=20)
    slug = AutoSlugField(set_using='name')
    deutero = models.BooleanField(default=False)
    about = models.CharField(max_length=500, blank=True)

    class Meta:
        ordering = ["position", "testament", "name"]

    def version_name(self):
        return self.version.name

    def __str__(self):
        return self.name

class Chapter(TimeStampedModel):
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    number = models.IntegerField()

    class Meta:
        ordering = ("book", "number")

    def book_name(self):
        return self.book.name

    def __str__(self):
        return f'{self.book.name.title()} {self.number}'

class Verse(TimeStampedModel):
    chapter = models.ForeignKey(Chapter, on_delete=models.CASCADE)
    number = models.IntegerField()
    text = models.CharField(max_length=600)

    class Meta:
        ordering = ["chapter", "number"]

    def book_name(self):
        return self.chapter.book.name

    def chapter_number(self):
        return self.chapter.number

    def __str__(self):
        return f'{self.chapter.book.name.title()} {self.chapter.number}: {self.number}'

drb/templates/drb/challoner.html
{% extends "ethodoxy_base.html" %}
{% block title %}Challoner commentary{% endblock title %}
{% block introduction %}{% endblock introduction %}


{% block breadcrumb %}
    <li class="breadcrumb-item active" aria-current="page">Challoner commentary</li>
{% endblock breadcrumb %}

{% block  content_content %}

<div class='container siteuser-index-heading'>
    <div class='row'>
        <h3 class='float-left'>Challoner commentary</h3>
    </div>
</div>
    
<div class="container">
    <div class="row">
        {% for commentary in commentaries %}
            <div class="col-sm-12 single-commentary-entry">
                <h4 class="text-success">{{ commentary.commentary_source.title }}</h4>
                <h6>{{ commentary.heading }}</h6>
                <p>{{ commentary.text }}</p>
            </div>
    
            {% empty %}
                <p style="margin-bottom:25rem">Coming soon</p>                
            {% endfor %}
    </div>
</div>
{% endblock content_content %}

drb/templates/drb/commentary_index.html
{% extends "catholic_base.html" %}
{% block title %}Challoner commentary{% endblock title %}
{% block introduction %}{% endblock introduction %}
{% block  content_content %}

<div class='container siteuser-index-heading'>
    <div class='row'>
        <h3 class='float-left'>Challoner commentary</h3>
    </div>
</div>
    
<div class="container">
    <div class="row">
        {% for commentary in commentaries %}
            <div class="col-sm-12 single-commentary-entry">
                <h4 class="text-success">{{ commentary.commentary_source.title }}</h4>
                <h6>{{ commentary.heading }}</h6>
                <p>{{ commentary.text }}</p>
            </div>
    
            {% empty %}
                <p style="margin-bottom:25rem">Coming soon</p>                
            {% endfor %}
    </div>
</div>
{% endblock content_content %}

drb/templates/drb/single_page_view.html
{% extends "catholic_base.html" %}
{% block title %}Douay-Rheims bible{% endblock title %}
{% block introduction %}{% endblock introduction %}
{% load drb_ttags_and_filters %}
{% block  content_content %}

<div class="container" id="vue-instance">
    <div class="row" id="show-current-location">
        <h6 class='float-left'>${ bible_version }$${ book_name }$${ chapter_number }$</h6>
    </div>

    <div class="row">
        <div class="col-sm-2 book-listing">

            {% for book in books %}

                <div id="accordion">
                    <div class="book-names" id="{{ book.name }}{{ forloop.counter }}">
                        <button class="btn btn-md text-left book-name-buttons" data-toggle="collapse" data-target="#Collapse{{ forloop.counter }}" aria-expanded="true" aria-controls="collapse{{ forloop.counter }}">
                            {{ book.name.title }}
                        </button>
                    </div>

                        <div id="Collapse{{ forloop.counter }}" class="collapse" aria-labelledby="{{ book.name }}{{ forloop.counter }}" data-parent="#accordion">
                            {% for chapter in book.chapter_set.all %}
                                <p class="chapter-number-paragraph"><button class="btn btn-sm text-left chapter-buttons" v-on:click="getVerses({{ chapter.pk }}, '{{ chapter.book.name.title }}', {{ chapter.number }})">{{ chapter }}</button></p>
                            {% endfor %}
                        </div>
                </div>
            {% endfor %}
        </div>
        <div class="col-sm-10 pr-0" id="book-text" style="width:100%">
            <h2 id="intro">Click the buttons to the left to open a chapter</h2>
            <p class="show-verse-text" v-for="(text, index) in bible_text"><strong>${ index }$:</strong> ${ text }$</p>
        </div>
        
    </div>
</div>

{% endblock content_content %}


{% block page_js %}

<script>
    new Vue({
        el: '#vue-instance',
        delimiters: ['${', '}$'],
        data : {
            chapter: '',
            books: [],
            bible_text: "",
            book_name: "",
            chapter_number: "",
            bible_version: "",
        },
        mounted : function() {
        },
        methods: {
            getVerses:function (pk, book_name, chapter_number) {
                // remove shown text if it exists
                var elem = document.getElementById("intro");
                if (elem) {
                    elem.remove();
                }

                //get data
                this.$http.get("/douay-rheims/chapter/" + pk)
                    .then((response) => {
                        console.log(response.data)
                        this.bible_text = response.data
                    });
                $('#show-current-location').addClass('top-heading')
                this.bible_version = "Douay-Rheims bible",
                this.book_name = ' >> ' + book_name;
                this.chapter_number = ' >> ' + chapter_number

                //scroll to top of page
                document.body.scrollTop = document.documentElement.scrollTop = 0;
            },
        },
    })

</script>
{% endblock page_js %}